"""Localized cover, navigation, and contact labels for all manual editions."""

LABELS = {
    "en": {
        "manual": "USER MANUAL", "audience": "USER AND OAI USER",
        "subtitle": "A complete guide to options and features for User and OAI User.",
        "topics": "INSTITUTIONAL DISCOVERY · ANALYTICS · DATA QUALITY · INTEGRATION",
        "version": "VERSION", "update": "UPDATED", "for": "AUDIENCE",
        "roles": "User / OAI User", "contents": "Contents", "figure": "FIGURE",
        "page": "PAGE", "note": "IMPORTANT", "contact": "CONTACT INFORMATION",
        "contents_note": "All five editions have the same content and page numbering. Screenshots and control names use each edition's language. This manual is limited to User and OAI User.",
        "quick_access": "Quick access to new workflows",
        "phone": "Telephone +56 2 2365 4589", "address": "Moneda 1375, 13th floor", "city": "Santiago, Chile",
    },
    "es": {
        "manual": "MANUAL DE USUARIO", "audience": "USUARIO Y USUARIO OAI",
        "subtitle": "Guía integral de opciones y funcionalidades de Usuario y Usuario OAI.",
        "topics": "CONSULTA INSTITUCIONAL · ANALÍTICAS · CALIDAD DE DATOS · INTEGRACIÓN",
        "version": "VERSIÓN", "update": "ACTUALIZACIÓN", "for": "AUDIENCIA",
        "roles": "Usuario / Usuario OAI", "contents": "Contenido", "figure": "FIGURA",
        "page": "PÁGINA", "note": "IMPORTANTE", "contact": "INFORMACIÓN DE CONTACTO",
        "contents_note": "Las cinco ediciones tienen el mismo contenido y numeración de páginas. Las capturas y los nombres de los controles se presentan en el idioma de cada edición. Este manual se limita a Usuario y Usuario OAI.",
        "quick_access": "Accesos rápidos a las novedades",
        "phone": "Teléfono +56 2 2365 4589", "address": "Moneda 1375, piso 13", "city": "Santiago de Chile",
    },
    "fr": {
        "manual": "MANUEL D’UTILISATION", "audience": "UTILISATEUR ET UTILISATEUR OAI",
        "subtitle": "Guide des options et fonctions pour Utilisateur et Utilisateur OAI.",
        "topics": "CONSULTATION INSTITUTIONNELLE · ANALYSES · QUALITÉ DES DONNÉES · INTÉGRATION",
        "version": "VERSION", "update": "MISE À JOUR", "for": "PUBLIC",
        "roles": "Utilisateur / Utilisateur OAI", "contents": "Sommaire", "figure": "FIGURE",
        "page": "PAGE", "note": "IMPORTANT", "contact": "COORDONNÉES",
        "contents_note": "Les cinq éditions ont le même contenu et la même pagination. Les captures et les noms des commandes suivent la langue de chaque édition. Ce manuel concerne uniquement Utilisateur et Utilisateur OAI.",
        "quick_access": "Accès rapide aux nouvelles fonctions",
        "phone": "Téléphone +56 2 2365 4589", "address": "Moneda 1375, 13e étage", "city": "Santiago, Chili",
    },
    "pt": {
        "manual": "MANUAL DO USUÁRIO", "audience": "USUÁRIO E USUÁRIO OAI",
        "subtitle": "Guia completo das opções e funções de Usuário e Usuário OAI.",
        "topics": "CONSULTA INSTITUCIONAL · ANÁLISES · QUALIDADE DOS DADOS · INTEGRAÇÃO",
        "version": "VERSÃO", "update": "ATUALIZAÇÃO", "for": "PÚBLICO",
        "roles": "Usuário / Usuário OAI", "contents": "Sumário", "figure": "FIGURA",
        "page": "PÁGINA", "note": "IMPORTANTE", "contact": "INFORMAÇÕES DE CONTATO",
        "contents_note": "As cinco edições têm o mesmo conteúdo e a mesma numeração de páginas. Capturas e nomes dos controles seguem o idioma de cada edição. Este manual se limita a Usuário e Usuário OAI.",
        "quick_access": "Acesso rápido às novas funções",
        "phone": "Telefone +56 2 2365 4589", "address": "Moneda 1375, 13º andar", "city": "Santiago, Chile",
    },
    "de": {
        "manual": "BENUTZERHANDBUCH", "audience": "NUTZER UND OAI-NUTZER",
        "subtitle": "Umfassender Leitfaden für die Rollen Nutzer und OAI-Nutzer.",
        "topics": "INSTITUTIONELLE RECHERCHE · ANALYSEN · DATENQUALITÄT · INTEGRATION",
        "version": "VERSION", "update": "AKTUALISIERT", "for": "ZIELGRUPPE",
        "roles": "Nutzer / OAI-Nutzer", "contents": "Inhalt", "figure": "ABBILDUNG",
        "page": "SEITE", "note": "WICHTIG", "contact": "KONTAKTINFORMATIONEN",
        "contents_note": "Alle fünf Ausgaben haben denselben Inhalt und dieselbe Seitennummerierung. Abbildungen und Bezeichnungen der Bedienelemente folgen der jeweiligen Sprache. Dieses Handbuch gilt ausschließlich für Nutzer und OAI-Nutzer.",
        "quick_access": "Direkt zu den neuen Funktionen",
        "phone": "Telefon +56 2 2365 4589", "address": "Moneda 1375, 13. Stock", "city": "Santiago, Chile",
    },
}
