"""Agregar tabla ResearcherCache

Revision ID: 1f5c3eb504eb
Revises: 9c6bbf9c71fe
Create Date: 2026-02-12 17:43:06.136712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f5c3eb504eb'
down_revision = '9c6bbf9c71fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researcher_cache',
    sa.Column('orcid', sa.String(length=32), nullable=False),
    sa.Column('given_names', sa.String(length=150), nullable=True),
    sa.Column('family_name', sa.String(length=150), nullable=True),
    sa.Column('credit_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('orcid')
    )
    with op.batch_alter_table('researcher_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_researcher_cache_orcid'), ['orcid'], unique=False)

    with op.batch_alter_table('orcid_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orcid_cache_year'), ['year'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_ror_id'), ['ror_id'], unique=False)

    with op.batch_alter_table('work_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_cache_doi'), ['doi'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_cache_doi'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_ror_id'))

    with op.batch_alter_table('orcid_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orcid_cache_year'))

    with op.batch_alter_table('researcher_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_researcher_cache_orcid'))

    op.drop_table('researcher_cache')
    # ### end Alembic commands ###
