"""Agrega ResearcherStatus y grid_id

Revision ID: 8d2214b58e8d
Revises: dab46988711b
Create Date: 2026-02-05 11:49:41.523206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d2214b58e8d'
down_revision = 'dab46988711b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_cache_run', schema=None) as batch_op:
        batch_op.drop_column('total_orcids')
        batch_op.drop_column('processed_orcids')
        batch_op.drop_column('processed_works')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_cache_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed_works', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('processed_orcids', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_orcids', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
