"""empty message

Revision ID: 9c6bbf9c71fe
Revises: 8d2214b58e8d
Create Date: 2026-02-11 18:16:55.342820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6bbf9c71fe'
down_revision = '8d2214b58e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('am_client_id', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('am_client_id')

    # ### end Alembic commands ###
