<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:mapped="https://dataorcid.cl/ns/mapped-metadata/1.0/"
           targetNamespace="https://dataorcid.cl/ns/mapped-metadata/1.0/"
           elementFormDefault="qualified">
  <xs:element name="record">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="field" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType mixed="true">
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="source" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="schemaVersion" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>
